name: tropical-width
channels: 
  - nodefaults
  - conda-forge
dependencies: 
  - python==3.13.5
  - pip
  - jupyter
  - awscli 
  - boto3 
  - netCDF4
  - numpy
  - earthaccess
  - matplotlib
  - cartopy
  - pip: 
    - ./tropicalwidth
